# (from: https://qiita.com/masashi127/items/5bfcba5cad8e82958844)

language: python

python:
  - 3.4
  - 3.5
  - 3.6


before_install:
  - pip install -U pip setuptools wheel # (from: https://github.com/dnouri/nolearn/blob/master/.travis.yml)

install:
  - travis_wait travis_retry pip install -r requirements.txt # (from: https://github.com/dnouri/nolearn/blob/master/.travis.yml)

script:
  - python3 setup.py test
#  (This is for coveralls: If this repository is public, Recomment it out and remove 'python3 setup.py test')
#  - coverage run --source=rubyize setup.py test

#  # Example run
#  - pip3 install --upgrade git+https://github.com/nwtgck/rubyize-python.git#$TRAVIS_COMMIT
#  - python examples/example1.py

#after_success:
#  - coveralls

cache:
  - apt
  - directories:
    - $HOME/.cache/pip